= class Exception < Object

全ての例外の祖先のクラスです。


== Class Methods

--- new(error_message = nil)       -> Exception
--- exception(error_message = nil) -> Exception

예외 객체를 리턴합니다.

@param error_message エラーメッセージを表す文字列を指定します。このメッセージは
                     属性 [[m:Exception#message]] の値になり、デフォルトの例外ハンドラで表示されます。


== Instance Methods

--- exception                   -> self
--- exception(error_message)    -> Exception

引数を指定しない場合は self を返します。引数を指定した場合 自身のコピー
を生成し [[m:Exception#message]] 属性を error_message にして返します。

[[m:Kernel.#raise]] は、実質的に、例外オブジェクトの exception
メソッドの呼び出しです。

@param error_message エラーメッセージを表す文字列を指定します。

  begin
   ...        # 무언가 처리하는 코드
  rescue => e
   raise e.exception("an error occurs during hogehoge process")  # 상세한 에러 메시지
  end

--- backtrace    -> [String]

バックトレース情報を返します。

デフォルトでは

  * "#{sourcefile}:#{sourceline}:in `#{method}'"
    (メソッド内の場合)
  * "#{sourcefile}:#{sourceline}"
    (トップレベルの場合)

という形式の [[c:String]] の配列です。

 def methd
   raise
 end
 
 begin
   methd
 rescue => e
   p e.backtrace
 end
 
 #=> ["filename.rb:2:in `methd'", "filename.rb:6"]

--- message    -> String
--- to_s       -> String
#@until 1.9.1
--- to_str    -> String
#@end

エラーメッセージをあらわす文字列を返します。

  begin
    1 + nil
  rescue => e
    p e.message   #=>  "nil can't be coerced into Fixnum"
  end

--- set_backtrace(errinfo)    -> nil | String | [String]

バックトレース情報に errinfo を設定し、設定されたバックトレース
情報を返します。

@param errinfo nil、[[c:String]] あるいは [[c:String]] の配列のいずれかを指定します。

#@since 1.9.1
--- ==(other)    -> bool

自身と指定された other のクラスが同じであり、message と backtrace が == メソッドで比較して
等しい場合に true を返します。그렇지 않으면 false를 리턴합니다.

@param other self와 비교하려는 객체를 지정합니다.

#@end